apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
    env: prod
    version: "1.0.0"
  name: hands-on
  namespace: user-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
      env: prod
      version: "1.0.0"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hands-on
        env: prod
        version: "1.0.0"
    spec:
      containers:
      - image: nginx:latest
        name: foobar
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: DB_HOST
          value: "192.168.0.1"
        - name: DB_NAME
          value: "foobar"
        ports:
          - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: / 
            port: 80
            httpHeaders:
            - name: kubelet-probe
              value: "true"
          initialDelaySeconds: 5
          periodSeconds: 10

